name: stratilj-whalebone

services:
  postgres:
    build: docker/postgres

  composer:
    image: composer:latest
    volumes:
      - ./src/:/app/
    command: composer install --ignore-platform-reqs --no-scripts

  php:
    build: docker/php
    depends_on:
      - postgres
      - composer
    volumes:
      - ./src/:/var/whalebone/

  nginx:
    build: docker/nginx
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./src/www/:/var/whalebone/www/
